### ISSUE TITLE
TerraformExplore

### ISSUE THREAD

**Issue by AaronJohnsonValtech** [mvaldes14/terraform.nvim#6]
When using the explorer and a resource has a large output I am unable to scroll in the telescope view. Is it just me or is this a bug?

**Comment by mvaldes14** [comment]
do you mean the preview window?
if so - i'd need to check if there is a limit on how much the preview viewport will allow.

can you tell me how many lines that resource has?

**Comment by AaronJohnsonValtech** [comment]
If you're trying to re-create it, just shrink your terminal window 😉
Telescope has scrolling and it works when previewing files, just not with this plugin.

**Comment by mvaldes14** [comment]
odd i can't even get the preview window outside of this project to scroll up or down... using the default keymaps.
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/mappings.lua#L149C22-L149C22
