### ISSUE TITLE
Remote state

### ISSUE THREAD

**Issue by thesimonho** [mvaldes14/terraform.nvim#7]
would it be possible to explore state that is stored remotely (eg on s3)?

**Comment by mvaldes14** [comment]
if you can do it via cli you should be able to see it within the plugin, it simply calls terraform state list and parses the output.
give it a go and let me know!

i keep my state in hashicorp cloud and it works fine.

**Comment by thesimonho** [comment]
ah I see what the problem is:

1. im in a monorepo where the working directory is the root. i assumed the plugin was running tf state list on the directory of the current file - is there an option to set this instead?
2. when I manually set the working directory and run TerraformExplore, everything shows up. However, I get an error when pressing RET on any of the items. problem is that I'm on windows where grep is not available. the closest I have installed is rg. Is there a way to set which program is run to do the search?
```
   Error  1:10:52 AM msg_show.emsg E5108: Error executing lua: ...ta/Local/nvim-data/lazy/plenary.nvim/lua/plenary/job.lua:108: grep: Executable not found
stack traceback:
	...ta/Local/nvim-data/lazy/plenary.nvim/lua/plenary/job.lua:108: in function 'new'
	...a/lazy/terraform.nvim/lua/terraform/telescope_picker.lua:19: in function 'find_lnum_in_file'
	...a/lazy/terraform.nvim/lua/terraform/telescope_picker.lua:59: in function 'run_replace_or_original'
	...im-data/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:292>
```

**Comment by mvaldes14** [comment]
that makes sense yeah we can specify which binary to use as an option for the plugin to use it. grep and rg are fairly similar option wise, let me cook an update.

**Comment by mvaldes14** [comment]
reworked a lot of things and added some options for users to pick - see #8

**Comment by SimonHoSprung** [comment]
@mvaldes14 the state list now works, thanks

but im getting an error when I RET on any of the items:

```
   Error  1:35:43 PM msg_show.emsg E5108: Error executing lua: ...l/nvim-data/lazy/terraform.nvim/lua/terraform/picker.lua:60: attempt to concatenate field 'path' (a nil value)
stack traceback:
	...l/nvim-data/lazy/terraform.nvim/lua/terraform/picker.lua:60: in function 'run_replace_or_original'
	...im-data/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:292>
```

not sure if this is because rg is not running correctly, or because of a path/separator difference when running this on windows

**Comment by thesimonho** [comment]
@mvaldes14 the state list now works, thanks

but I'm getting an error when I RET on any of the items:

```
   Error  1:35:43 PM msg_show.emsg E5108: Error executing lua: ...l/nvim-data/lazy/terraform.nvim/lua/terraform/picker.lua:60: attempt to concatenate field 'path' (a nil value)
stack traceback:
	...l/nvim-data/lazy/terraform.nvim/lua/terraform/picker.lua:60: in function 'run_replace_or_original'
	...im-data/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:292>
```

not sure if this is because rg is not running correctly, or because of a path/separator issue when running this on windows
